name: Sync with the upstream repository

on:
  schedule:
    - cron: "0 5 30 * *"
  workflow_dispatch: {}

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sync the upstream's repository contents
        run: |
          git remote add --fetch "upstream" "https://github.com/koalaman/shellcheck-precommit.git"
          git config set "user.name" "github-actions[bot]"
          git config set "user.email" "41898282+github-actions[bot]@users.noreply.github.com"
          git merge "upstream/master"
          git push "origin" "master"
